name: gotham_lints
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

dependencies:
  analysis_server_plugin: ^0.3.0
  analyzer: ^8.4.0
  analyzer_plugin: ^0.13.7
  collection: ^1.19.1

dev_dependencies:
  analyzer_testing: ^0.1.2
  test: any
  test_reflective_loader: any
